### ISSUE TITLE
Forecast Data

### ISSUE THREAD

**Issue by azampagl** [azampagl/harvard-capstone#3]
See if we can find forecast data.

**Comment by micahlanier** [comment]
I haven't been able to find anything on this front so far, save for some national-level graphical forecast archives from the Climate Prediction Center. Those don't look promising. If we do find anything, I'm not sure it will add much more predictive power than actual observed weather.

**Comment by azampagl** [comment]
For now, I'm creating "predictions" based on the day before's actuals... I'd hope the weather predictions are fairly accurate within one day.
