### ISSUE TITLE
Weather Data Evaluation

### ISSUE THREAD

**Issue by azampagl** [azampagl/harvard-capstone#6]
Evaluate the current weather data available for Boston.

**Comment by micahlanier** [comment]
No luck so far with the dataset that NOAA generated. Few records even appear to have information as simple as temperature, and those that do often have absurd values (e.g., -189 degrees for a min temp). I'll review documentation further and take another look at NOAA datasets for an alternative.

**Comment by micahlanier** [comment]
Added code to retrieve daily NCDC snowfall records and saved that data locally. Now investigating Weather Underground API for historical data. This looks like a promising aggregation of historical data and might give us exactly what we're looking for.

**Comment by micahlanier** [comment]
I managed to pull daily observations from 1/2013 through 1/2015 from the Weather Underground API. Data looks very clean and should save us the trouble of aggregating figures from multiple weather stations in metro Boston. I just have some final sanity checking to do to square NCDC data and WU data to ensure the latter's reliability.

**Comment by micahlanier** [comment]
NCDC and WU data match almost exactly. The WU data should be what we need for now.
